# Generated by Django 3.0.4 on 2020-04-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='p_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
